apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "enmasse.io:iot-device-connection-amq-online-infra"
  labels:
    app: enmasse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: enmasse.io:iot-device-connection
subjects:
- kind: ServiceAccount
  name: iot-device-connection
  namespace: amq-online-infra
